### ISSUE TITLE
write.plink() assumes human genome

### ISSUE THREAD

**Issue by ekirving** [NikNakk/snpStats#1]
Hello,

Firstly, thank you very much for making a really useful package!

I am, however, encountering an issue where there is a [hardcoded assumption in plink.R](https://github.com/NikNakk/snpStats/blob/master/R/plink.R#L213) that the data being written by `write.plink()` is human.

I am using this library to manipulate plink data containing cattle genomes, which have more than 22 autosomes. Reading in the data with `read.plink()` works fine, but writing it back out causes the following fatal error:
> unrecognized chromosome name

It would be ideal if there was a flag which could turn off the chromosome name validation (or if it was simply removed altogether). For example, the latest cattle reference genome [Btau_5.0.1](https://www.ncbi.nlm.nih.gov/assembly/GCF_000003205.7/) has 3,112 unplaced scaffolds in addtion to the normal 29 autosomes.

Thanks!

**Comment by NikNakk** [comment]
Hi, Sorry to disappoint, but I’m not the maintainer of snoStats. I created this repo when I was trying to troubleshoot a problem with the package, but it’s maintained by David Clayton dc208@cam.ac.uk. I’d suggest emailing him with your query.

**Comment by ekirving** [comment]
Ah, thanks. Sorry for the confusion.
